### ISSUE TITLE
Translate Result!

### ISSUE THREAD

**Issue by MohMehrnia** [SAH-UJA/topsis#1]
I run below code :
```
if __name__ == '__main__':
    top_obj = topsis.Topsis('data.csv')
    w = [0.35, 0.25, 0.25, 0.15]
    im = ["+", "+", "+", "-"]
    decision = top_obj.evaluate(w, im)
    print(decision)
```

and with 4 feature result is below:
`[[0, 0.723493340132304, 2], [1, 0.21605962030933276, 3], [2, 0.7983550013401491, 1]]
`
why result is 3 element i excepted 4 element
and data.csv is:

```
250,16,12,5
200,16,8,3
275,32,8,40
225,16,16,2

```
why? How do translate result?

**Comment by SAH-UJA** [comment]
You need to have another tuple too for the headings. Just add one more tuple at the starting in data.csv denoting the feature names like (you can have some other names of features too) :

A,B,C,D
250,16,12,5
200,16,8,3
275,32,8,40
225,16,16,2
